### ISSUE TITLE
Error when loading datapack on 1.20.1

### ISSUE THREAD

**Issue by Fisch37** [Fisch37/waypoints-vanilla#4]
Running version 1.0-beta.5 on Minecraft 1.20.1 the datapack fails to load with the following error:
```
[Render thread/ERROR]: Failed to load function fisch37:waypoints/book_modifiers/relative/_iter_page_generation
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 8: Expected integer at position 65: ...un return <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 8: Expected integer at position 65: ...un return <--[HERE]
	at net.minecraft.class_2158.method_9195(class_2158.java:63) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5349.method_29451(class_5349.java:83) ~[transformed-mod-minecraft.i0:0/:?]
	... 7 more
```

First analysis implies this is caused by the following LOC in `fisch37:waypoints/book_modifiers/relative/_iter_page_generation`:
```
# Failsafe for wps_count > 128 (or other value if implementation changed)
execute unless data storage fisch37:json templates[0] run return fail
```
Critical component is `return fail` which is a command only added in 1.20.4. This may cause book generation to fail in versions 1.20.1-1.20.3. Further testing is required.

**Comment by Fisch37** [comment]
This error was introduced on commit [` baeb7a1`](https://github.com/Fisch37/waypoints-vanilla/commit/baeb7a1dc7c558596c5e47d3521e440a95070c03) fixing #2.
